version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 1s
      retries: 3
      start_period: 1s
  app:
    build:
      context: .
    depends_on:
      redis:
        condition: service_healthy

